### ISSUE TITLE
Difference between Flamingo and Pelican

### ISSUE THREAD

**Issue by PhilipMay** [pengutronix/flamingo#11]
Hi,
I am interested in the main differences between Flamingo and Pelican. Why did you start coding this and not just use pelican? What is the problem you want to solve that is not solved by pelican?

Maybe this is something other ppl are interested in. IMHO it would be nice to include it in the README because it might be a pro argument to use your software...

Thanks
Philip

**Comment by fscherf** [comment]
Hi @PhilipMay,

Great question! Flamingo is a much smaller Pelican rewrite, i started coding for the website of my company after painful years of pelican use.

> Why did you start coding this and not just use pelican?

When i started using pelican for my company's website, i got a todo list of requested features and URL schemes. In most cases, pelican, and pelican plugins, define a specific way to solve a problem. If your use case is a bit of, you have to write much custom code.

For example: Pelican has a plugin for internationalization but it produces URL schemes that don't fit in our pre designed url schemes. To change the urls because the tool is not capable to them like i want was not acceptable, so i wrote a custom internationalization plugin and realized that many of the bad things of pelican's internationalization plugin are because of the lack of proper pelican apis and the very static data model.

> What is the problem you want to solve that is not solved by pelican?

Like i mentioned before pelican has very specific ways to solve problems. Every part of Flamingo is designed to be extensible and configurable. When Flamingo solves a problem for you, that's not **the** way to do it, it is **one** way that @fscherf suggests, and most changes can be done through configuration, a simple hook or meta data in content files. For the most things you don't have to write a plugin because i want the tool out of the way of the people that just want to write content. 

Yes you can do great things in Pelican, but in most cases the resulting code is higher magic. 

All employees of www.pengutronix.de write content only, no plugin code, no templates etc.
In times we used pelican i was the only one who was able to fix breaking pelican builds. So no repairs when i am on vacation.

With flamingo things are so dead simple and easy to debug (flamingo comes with actual debug tools build in) my coworkers actually start to fix problems on their own or can produce proper bug-reports at least.

Greetings,
@fscherf

**Comment by PhilipMay** [comment]
Ok - thanks. 👍

**Comment by rohieb** [comment]
Also see this talk of @fscherf yesterday (in German though): https://media.ccc.de/v/froscon2019-2368-warum_flamingos_die_besseren_pelicane_sind

**Comment by PhilipMay** [comment]
Thanks for the answer. I found ABlog and love it. It's a blog extension to Sphinx.
Do you know that?

**Comment by fscherf** [comment]
@PhilipMay yes, but i am no fan of sphinx.

flamingo is not meant to be a blogging engine in particular, it is meant to be a simple framework for any kind of static websites.
