### ISSUE TITLE
HTML-Parser altering structure of document

### ISSUE THREAD

**Issue by SmithChart** [pengutronix/flamingo#15]
In flamingo v0.11 the HTML parser (`flamingo/plugins/html.py`) has a tendency to alter the structure of HTML documents. 

In my current project with `HTML_PARSER_RAW_HTML = False` I can reproduce the behavior with this HTML document. (`[...]` means that there is some content left out.)

```
template: raw.html


    <div class="main">
        <div>
            <a href="/">Zurück zur Hauptseite</a><br><br>
[...]
        <h4>Cookies</h4>
        <p>Diese Webseite verwendet keine Cookies oder ähnliche Technologien.</p>

        </div>
        <h2 id="footnote">Eine Veranstaltung des <a href="https://stratum0.org">Stratum 0</a></h2>
        <a style="display:none;" rel="me" href="https://chaos.social/@HackenOpenAir">Mastodon</a>
    </div>
```

This generates the following output:

```
 <div class="main">
<div>
<a href="/">Zurück zur Hauptseite</a><br><br>
[...]
<h4>Externe Inhalte</h4>
<p>Zur Darstellung der Webseite werden Inhalte von www.openstreetmap.org nachgeladen.</p>
<h4>Cookies</h4>
<p>Diese Webseite verwendet keine Cookies oder ähnliche Technologien.</p>
</p></br></br></br></br></br></br></div>
<h2 id="footnote">Eine Veranstaltung des <a href="https://stratum0.org">Stratum 0</a></h2>
<a href="https://chaos.social/@HackenOpenAir" rel="me" style="display:none;">Mastodon</a>
</div>
```

The main problem here are the extra `</p></br></br></br></br></br></br>` that are inserted by the HTML-parser.

I understand that Beautiful Soup is used to alter the src-attributes of images when using the media-API. But in most use-cases an altered HTML-structure as a whole is not acceptable.

When setting `HTML_PARSER_RAW_HTML = True` this behavior disappears.

**Comment by fscherf** [comment]
Hi @SmithChart,

The problem is this line:
```html
<a href="/">Zurück zur Hauptseite</a><br><br>
```
Beautiful Soup supports a [list](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser) of html parser. Flamingo uses `html.parser` because it has no further dependencies.
`html.parser` does not support single tags without a trailing slash, so you would need to write `<br />`
instead of `<br>`. 

[https://www.crummy.com/software/BeautifulSoup/bs4/doc/#differences-between-parsers](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#differences-between-parsers)

**Comment by fscherf** [comment]
@SmithChart does this solve/explain your issue?

**Comment by SmithChart** [comment]
This solves and explains my isse. Thanks!
