### ISSUE TITLE
Suggestion: Change links in the base theme template from absolute to relative paths

### ISSUE THREAD

**Issue by AlarithUhde** [pengutronix/flamingo#25]
I'm not sure whether this would introduce new problems or if it's considered bad practice for some reason.

Problem:
When creating a new website with `make html` in e.g., ~/my-site/, some resources including bootstrap are not loaded properly. The reason is that some of the links in the base.html template are currently included with absolute paths:

`<link rel="stylesheet" href="/static/bootstrap-4.3.1/css/bootstrap.min.css">`
`<link rel="stylesheet" href="/static/custom.css">`
`<link rel="shortcut icon" href="/favicon.ico">`

This has puzzled me before, because the website looked fine in the live server but not when clicking on the html files directly. As a newcomer, this is a somewhat demotivating hurdle. Do you see any problem changing them to relative paths? E.g.:

`<link rel="stylesheet" href="static/bootstrap-4.3.1/css/bootstrap.min.css">`
`<link rel="stylesheet" href="static/custom.css">`
`<link rel="shortcut icon" href="favicon.ico">`

That would fix the problem and make it easier to get started or when creating projects meant for offline use. On the other hand, I'm not sure if that would break compatibility or some standards elsewhere.

**Comment by fscherf** [comment]
Hi @AlarithUhde,

relative urls like that  only work if all of your pages are in the same directory. Let's say you have a blog page behind the url
``/blog/2022/new-year-post.html`` and the page would link bootstrap like this ``<link rel="stylesheet" href="static/bootstrap-4.3.1/css/bootstrap.min.css">``, you bootstrap files would have to be in ``/blog/2022/``, and all other years too.

That's why pretty much every HTML page links it's static files with absolute urls.
